version: '3.9'

services:
  api:
    build: ./src/app
    container_name: onsort_api
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onsort.rule=Host(`api.on-sort.fr`)"
      - "traefik.http.routers.onsort.entrypoints=web"
      - "traefik.http.services.onsort.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=production
      - API_PORT=3000
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=onsort
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./src/app/uploads:/usr/src/app/uploads
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql: # <-- Ce bloc doit être parfaitement aligné avec 'api:'
    image: mysql:8.0
    container_name: onsort_db
    networks:
      - backend-net
    command: --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=onsort
    volumes:
      - mysqldata:/var/lib/mysql
      - ./src/bdd-dump/onsort.sql:/docker-entrypoint-initdb.d/onsort.sql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysqldata:

networks:
  backend-net:
    external: true